name: craftshop2
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.3






#----------------------PACKAGE DEPENDENCIES----------------------#
dependencies:
  flutter:
    sdk: flutter
# Utility Packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.2
  smooth_page_indicator: ^1.2.0+3


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  #state management
  get: ^4.6.6
  get_storage: ^2.1.1

  #product Specific
  readmore: ^2.2.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

#-------------Package end --------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  http: ^1.2.2
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true


# ------------------LOCAL ASSETS------------------
  assets:
    - assets/logos/
    - assets/images/user/
    - assets/images/
    - assets/images/banners/
    - assets/images/products/
    - assets/logos/logo_google.png
    - assets/images/signUp/mail-verify.png
    # Catagories
    - assets/icons/catagories/porcelain.png
    - assets/icons/catagories/knitting.png
    - assets/icons/catagories/sculpture.png
    - assets/icons/catagories/canvas.png
    - assets/icons/catagories/bracelet.png
    # banner
    - assets/images/banners/brand-gom.png
    - assets/images/banners/Banner-lang-da.jpg
    - assets/images/on_boarding_images/
    - assets/icons/brands/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
